spring:
  application:
    name: corehealth
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/corehealth}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

application:
  security:
    jwt:
      secret: ${JWT_SECRET:corehealth-super-secret-key-corehealth-super-secret-key}
      expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}
